#ddl_statements.py
ddl_statements = """
CREATE TABLE Endereco (
    ID_ENDERECO NUMBER PRIMARY KEY,
    RUA VARCHAR2(100),
    NUMERO VARCHAR2(10),
    COMPLEMENTO VARCHAR2(50),
    BAIRRO VARCHAR2(50),
    CIDADE VARCHAR2(50),
    ESTADO VARCHAR2(2),
    CEP VARCHAR2(10)
);

CREATE TABLE Loja (
    ID_LOJA NUMBER PRIMARY KEY,
    NOME_LOJA VARCHAR2(100),
    ENDERECO NUMBER,
    FOREIGN KEY (ENDERECO) REFERENCES Endereco(ID_ENDERECO)
);

CREATE TABLE Cliente (
    ID_CLIENTE NUMBER PRIMARY KEY,
    NOME_CLIENTE VARCHAR2(100),
    EMAIL VARCHAR2(100),
    TELEFONE VARCHAR2(15),
    ENDERECO NUMBER,
    FOREIGN KEY (ENDERECO) REFERENCES Endereco(ID_ENDERECO)
);

CREATE TABLE Vendedor (
    ID_VENDEDOR NUMBER PRIMARY KEY,
    NOME_VENDEDOR VARCHAR2(100),
    HORARIO_ENTRADA VARCHAR2(5),
    HORARIO_SAIDA VARCHAR2(5),
    SALARIO NUMBER
);

CREATE TABLE Blusa (
    ID_BLUSA NUMBER PRIMARY KEY,
    NOME_BLUSA VARCHAR2(100),
    DESCRICAO VARCHAR2(255),
    PRECO NUMBER,
    MARCA VARCHAR2(50),
    COR VARCHAR2(20),
    TAMANHO VARCHAR2(10)
);

CREATE TABLE Calca (
    ID_CALCA NUMBER PRIMARY KEY,
    NOME_CALCA VARCHAR2(100),
    DESCRICAO VARCHAR2(255),
    PRECO NUMBER,
    MARCA VARCHAR2(50),
    COR VARCHAR2(20),
    TAMANHO VARCHAR2(10)
);

CREATE TABLE Saia (
    ID_SAIA NUMBER PRIMARY KEY,
    NOME_SAIA VARCHAR2(100),
    DESCRICAO VARCHAR2(255),
    PRECO NUMBER,
    MARCA VARCHAR2(50),
    COR VARCHAR2(20),
    TAMANHO VARCHAR2(10)
);

CREATE TABLE Acessorio (
    ID_ACESSORIO NUMBER PRIMARY KEY,
    NOME_ACESSORIO VARCHAR2(100),
    DESCRICAO VARCHAR2(255),
    PRECO NUMBER,
    MARCA VARCHAR2(50),
    TIPO VARCHAR2(50)
);

CREATE TABLE Bolsa (
    ID_BOLSA NUMBER PRIMARY KEY,
    NOME_BOLSA VARCHAR2(100),
    DESCRICAO VARCHAR2(255),
    PRECO NUMBER,
    MARCA VARCHAR2(50),
    COR VARCHAR2(20),
    TIPO VARCHAR2(50)
);

CREATE TABLE Perfume (
    ID_PERFUME NUMBER PRIMARY KEY,
    NOME_PERFUME VARCHAR2(100),
    DESCRICAO VARCHAR2(255),
    PRECO NUMBER,
    MARCA VARCHAR2(50),
    FRAGRANCIA VARCHAR2(50)
);

CREATE TABLE Pedido (
    ID_PEDIDO NUMBER PRIMARY KEY,
    DATA_PEDIDO DATE,
    HORARIO_PEDIDO VARCHAR2(5),
    VALOR_TOTAL NUMBER,
    ID_CLIENTE NUMBER,
    ID_VENDEDOR NUMBER,
    ID_LOJA NUMBER,
    TIPO_PEDIDO VARCHAR2(20),
    STATUS_PEDIDO VARCHAR2(20),
    FOREIGN KEY (ID_CLIENTE) REFERENCES Cliente(ID_CLIENTE),
    FOREIGN KEY (ID_VENDEDOR) REFERENCES Vendedor(ID_VENDEDOR),
    FOREIGN KEY (ID_LOJA) REFERENCES Loja(ID_LOJA)
);

CREATE TABLE PedidoTroca (
    ID_TROCA NUMBER PRIMARY KEY,
    ID_PEDIDO NUMBER,
    DATA_TROCA DATE,
    STATUS_TROCA VARCHAR2(20),
    DESCRICAO VARCHAR2(255),
    FOREIGN KEY (ID_PEDIDO) REFERENCES Pedido(ID_PEDIDO)
);

CREATE TABLE PedidoDevolucao (
    ID_DEVOLUCAO NUMBER PRIMARY KEY,
    ID_PEDIDO NUMBER,
    DATA_DEVOLUCAO DATE,
    STATUS_DEVOLUCAO VARCHAR2(20),
    DESCRICAO VARCHAR2(255),
    FOREIGN KEY (ID_PEDIDO) REFERENCES Pedido(ID_PEDIDO)
);

CREATE TABLE PedidoReembolso (
    ID_REEMBOLSO NUMBER PRIMARY KEY,
    ID_PEDIDO NUMBER,
    DATA_REEMBOLSO DATE,
    VALOR_REEMBOLSO NUMBER,
    STATUS_REEMBOLSO VARCHAR2(20),
    DESCRICAO VARCHAR2(255),
    FOREIGN KEY (ID_PEDIDO) REFERENCES Pedido(ID_PEDIDO)
);

CREATE TABLE PedidoCancelamento (
    ID_CANCELAMENTO NUMBER PRIMARY KEY,
    ID_PEDIDO NUMBER,
    DATA_CANCELAMENTO DATE,
    STATUS_CANCELAMENTO VARCHAR2(20),
    DESCRICAO VARCHAR2(255),
    FOREIGN KEY (ID_PEDIDO) REFERENCES Pedido(ID_PEDIDO)
);

CREATE TABLE Estoque (
    ID_ESTOQUE NUMBER PRIMARY KEY,
    ID_PRODUTO NUMBER,
    TIPO_PRODUTO VARCHAR2(20),
    QUANTIDADE NUMBER,
    ID_LOJA NUMBER,
    FOREIGN KEY (ID_LOJA) REFERENCES Loja(ID_LOJA)
);

CREATE TABLE PedidoProduto (
    ID_PEDIDO_PRODUTO NUMBER PRIMARY KEY,
    ID_PEDIDO NUMBER,
    ID_PRODUTO NUMBER,
    TIPO_PRODUTO VARCHAR2(20),
    QUANTIDADE NUMBER,
    VALOR_UNITARIO NUMBER,
    FOREIGN KEY (ID_PEDIDO) REFERENCES Pedido(ID_PEDIDO)
);

ALTER TABLE Estoque ADD CONSTRAINT fk_blusa FOREIGN KEY (ID_PRODUTO) REFERENCES Blusa(ID_BLUSA);
ALTER TABLE Estoque ADD CONSTRAINT fk_calca FOREIGN KEY (ID_PRODUTO) REFERENCES Calca(ID_CALCA);
ALTER TABLE Estoque ADD CONSTRAINT fk_saia FOREIGN KEY (ID_PRODUTO) REFERENCES Saia(ID_SAIA);
ALTER TABLE Estoque ADD CONSTRAINT fk_acessorio FOREIGN KEY (ID_PRODUTO) REFERENCES Acessorio(ID_ACESSORIO);
ALTER TABLE Estoque ADD CONSTRAINT fk_bolsa FOREIGN KEY (ID_PRODUTO) REFERENCES Bolsa(ID_BOLSA);
ALTER TABLE Estoque ADD CONSTRAINT fk_perfume FOREIGN KEY (ID_PRODUTO) REFERENCES Perfume(ID_PERFUME);

ALTER TABLE PedidoProduto ADD CONSTRAINT fk_blusa_pedido FOREIGN KEY (ID_PRODUTO) REFERENCES Blusa(ID_BLUSA);
ALTER TABLE PedidoProduto ADD CONSTRAINT fk_calca_pedido FOREIGN KEY (ID_PRODUTO) REFERENCES Calca(ID_CALCA);
ALTER TABLE PedidoProduto ADD CONSTRAINT fk_saia_pedido FOREIGN KEY (ID_PRODUTO) REFERENCES Saia(ID_SAIA);
ALTER TABLE PedidoProduto ADD CONSTRAINT fk_acessorio_pedido FOREIGN KEY (ID_PRODUTO) REFERENCES Acessorio(ID_ACESSORIO);
ALTER TABLE PedidoProduto ADD CONSTRAINT fk_bolsa_pedido FOREIGN KEY (ID_PRODUTO) REFERENCES Bolsa(ID_BOLSA);
ALTER TABLE PedidoProduto ADD CONSTRAINT fk_perfume_pedido FOREIGN KEY (ID_PRODUTO) REFERENCES Perfume(ID_PERFUME);
"""

